### ISSUE TITLE
Duvida 

### ISSUE THREAD

**Issue by amenezesw** [ericdouglas/mdn#1]
Opa @ericdouglas , tudo bem ?
Poderia explicar qual ideia deste projeto ? Tive uma ideia similar a que acho que é a tua, que é traduzir o material da MDN.
Se for não problemas, faço um fork e mando uns PR. 

Sucesso sempre!

**Comment by ericdouglas** [comment]
Não vou traduzir não @amenezesw , vou apenas fazer uns resumos.

Se for traduzir, traduza no próprio site da MDN!

Abraço e sucesso também parceiro :smile:
